# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GeoLearner.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 682)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0689655, y1:0.698864, x2:1, y2:0, stop:0.280788 rgba(96, 191, 186, 233), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.geoLabel = QtWidgets.QLabel(self.centralwidget)
        self.geoLabel.setGeometry(QtCore.QRect(133, 20, 601, 112))
        self.geoLabel.setStyleSheet("font: 96pt \"Helvetica Neue\";\n"
"border: 6px solid white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 246, 246, 251), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 5px;\n"
"")
        self.geoLabel.setObjectName("geoLabel")
        self.flagView = QtWidgets.QGraphicsView(self.centralwidget)
        self.flagView.setGeometry(QtCore.QRect(260, 180, 341, 241))
        self.flagView.setObjectName("flagView")
        self.countryLabel = QtWidgets.QLabel(self.centralwidget)
        self.countryLabel.setGeometry(QtCore.QRect(290, 430, 91, 31))
        self.countryLabel.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.countryLabel.setObjectName("countryLabel")
        self.capitalLabel = QtWidgets.QLabel(self.centralwidget)
        self.capitalLabel.setGeometry(QtCore.QRect(289, 500, 71, 21))
        self.capitalLabel.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.capitalLabel.setObjectName("capitalLabel")
        self.languageLabel = QtWidgets.QLabel(self.centralwidget)
        self.languageLabel.setGeometry(QtCore.QRect(269, 560, 91, 21))
        self.languageLabel.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.languageLabel.setObjectName("languageLabel")
        self.countryText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.countryText.setGeometry(QtCore.QRect(370, 430, 171, 31))
        self.countryText.setStyleSheet("")
        self.countryText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.countryText.setReadOnly(True)
        self.countryText.setObjectName("countryText")
        self.capitalText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.capitalText.setGeometry(QtCore.QRect(370, 500, 171, 31))
        self.capitalText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.capitalText.setReadOnly(True)
        self.capitalText.setObjectName("capitalText")
        self.languageText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.languageText.setGeometry(QtCore.QRect(370, 560, 171, 31))
        self.languageText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.languageText.setReadOnly(True)
        self.languageText.setObjectName("languageText")
        self.prevBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevBtn.setGeometry(QtCore.QRect(130, 270, 113, 32))
        self.prevBtn.setStyleSheet("font-size: 15px;\n"
"color: white;")
        self.prevBtn.setObjectName("prevBtn")
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setGeometry(QtCore.QRect(620, 270, 113, 32))
        self.nextBtn.setStyleSheet("font-size: 15px;\n"
"color: white;")
        self.nextBtn.setObjectName("nextBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.geoLabel.setText(_translate("MainWindow", "Geo Learner"))
        self.countryLabel.setText(_translate("MainWindow", "Country:"))
        self.capitalLabel.setText(_translate("MainWindow", "Capital:"))
        self.languageLabel.setText(_translate("MainWindow", "Language:"))
        self.prevBtn.setText(_translate("MainWindow", "PREVIOUS"))
        self.nextBtn.setText(_translate("MainWindow", "NEXT"))
