# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GeoLearner.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 682)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0689655, y1:0.698864, x2:1, y2:0, stop:0.280788 rgba(96, 191, 186, 233), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.geoLabel = QtWidgets.QLabel(self.centralwidget)
        self.geoLabel.setGeometry(QtCore.QRect(133, 20, 601, 112))
        self.geoLabel.setStyleSheet("font: 96pt \"Helvetica Neue\";\n"
"border: 6px solid white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 246, 246, 251), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius: 5px;\n"
"")
        self.geoLabel.setObjectName("geoLabel")
        self.countryLabel = QtWidgets.QLabel(self.centralwidget)
        self.countryLabel.setGeometry(QtCore.QRect(260, 430, 101, 31))
        self.countryLabel.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.countryLabel.setTextFormat(QtCore.Qt.PlainText)
        self.countryLabel.setObjectName("countryLabel")
        self.capitalLabel = QtWidgets.QLabel(self.centralwidget)
        self.capitalLabel.setGeometry(QtCore.QRect(270, 500, 101, 31))
        self.capitalLabel.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.capitalLabel.setObjectName("capitalLabel")
        self.languageLabel = QtWidgets.QLabel(self.centralwidget)
        self.languageLabel.setGeometry(QtCore.QRect(250, 560, 111, 31))
        self.languageLabel.setStyleSheet("font-size: 20px;\n"
"color: white;")
        self.languageLabel.setObjectName("languageLabel")
        self.countryText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.countryText.setEnabled(True)
        self.countryText.setGeometry(QtCore.QRect(350, 430, 231, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countryText.sizePolicy().hasHeightForWidth())
        self.countryText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(19)
        font.setItalic(True)
        self.countryText.setFont(font)
        self.countryText.setTabletTracking(False)
        self.countryText.setAcceptDrops(False)
        self.countryText.setAutoFillBackground(False)
        self.countryText.setStyleSheet("color: rgb(240, 255, 253);")
        self.countryText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.countryText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.countryText.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.countryText.setReadOnly(True)
        self.countryText.setPlainText("")
        self.countryText.setOverwriteMode(False)
        self.countryText.setCursorWidth(2)
        self.countryText.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.countryText.setCenterOnScroll(False)
        self.countryText.setObjectName("countryText")
        self.capitalText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.capitalText.setGeometry(QtCore.QRect(350, 500, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(19)
        font.setItalic(True)
        self.capitalText.setFont(font)
        self.capitalText.setStyleSheet("color: rgb(240, 255, 253);")
        self.capitalText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.capitalText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.capitalText.setReadOnly(True)
        self.capitalText.setObjectName("capitalText")
        self.languageText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.languageText.setGeometry(QtCore.QRect(350, 560, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(19)
        font.setItalic(True)
        self.languageText.setFont(font)
        self.languageText.setStyleSheet("color: rgb(240, 255, 253);")
        self.languageText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.languageText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.languageText.setReadOnly(True)
        self.languageText.setObjectName("languageText")
        self.prevBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevBtn.setGeometry(QtCore.QRect(130, 270, 113, 32))
        self.prevBtn.setStyleSheet("font-size: 15px;\n"
"color: white;\n"
"border: 1px solid black;")
        self.prevBtn.setObjectName("prevBtn")
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setGeometry(QtCore.QRect(620, 270, 113, 32))
        self.nextBtn.setStyleSheet("font-size: 15px;\n"
"color: white;\n"
"border: 1px solid black;")
        self.nextBtn.setObjectName("nextBtn")
        self.flagView = QtWidgets.QLabel(self.centralwidget)
        self.flagView.setEnabled(False)
        self.flagView.setGeometry(QtCore.QRect(250, 160, 351, 251))
        self.flagView.setStyleSheet("border: 6px solid white;")
        self.flagView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.flagView.setLineWidth(14)
        self.flagView.setText("")
        self.flagView.setScaledContents(True)
        self.flagView.setOpenExternalLinks(True)
        self.flagView.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.flagView.setObjectName("flagView")
        self.countryLabel.raise_()
        self.languageLabel.raise_()
        self.capitalLabel.raise_()
        self.geoLabel.raise_()
        self.countryText.raise_()
        self.capitalText.raise_()
        self.languageText.raise_()
        self.prevBtn.raise_()
        self.nextBtn.raise_()
        self.flagView.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.geoLabel.setText(_translate("MainWindow", "Geo Learner"))
        self.countryLabel.setText(_translate("MainWindow", "Country:"))
        self.capitalLabel.setText(_translate("MainWindow", "Capital:"))
        self.languageLabel.setText(_translate("MainWindow", "Language:"))
        self.prevBtn.setText(_translate("MainWindow", "PREVIOUS"))
        self.nextBtn.setText(_translate("MainWindow", "NEXT"))
